stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ajaysheoran2323/docker-nginx
      pushRemote: true
      registry: index.docker.io
- name: k8s-deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
- name: Done
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: echo "hellow world"
timeout: 60
notification: {}
