stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mylatestimage
- name: k8sdeployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
- name: done
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: print("hello")
timeout: 60
notification: {}
