stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ajaysheoran2323/docker-nginx
      pushRemote: true
      registry: index.docker.io
- name: done
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: echo "hello world"
timeout: 60
notification: {}
