apiVersion: v1
kind: ConfigMap
metadata:
    name: configmap-demo
    namespace: devops
    labels:
        app: nginx   
data:
    index.html: |
                "hello  world. Config map testing"
---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    namespace: devops
    labels:
        app: nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx  
    template:
        metadata: 
            name: nginx
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: ajaysheoran2323/docker-nginx:latest
                  imagePullPolicy: Always
                  volumeMounts:
                    mountPath: /usr/share/nginx/html
                    name: configmap-as-volume
                  
            volumes:
                - name: configmap-as-volume
                  configMap:
                    name: configmap-demo
                    
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    namespace: devops
    labels:
        app: nginx
spec:
    selector: 
        app: nginx
    ports:
        - name: http
          protocol: TCP
          port: 80
